/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVetRouteImport } from './routes/_app.vet'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppLearnRouteImport } from './routes/_app.learn'
import { Route as AppIotRouteImport } from './routes/_app.iot'
import { Route as AppImageAnalysisRouteImport } from './routes/_app.image-analysis'
import { Route as AppFarmsRouteImport } from './routes/_app.farms'
import { Route as AppDemoRouteImport } from './routes/_app.demo'
import { Route as AppDatasetRouteImport } from './routes/_app.dataset'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAssistantRouteImport } from './routes/_app.assistant'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppPredictionsIdRouteImport } from './routes/_app.predictions.$id'
import { Route as AppHealthRecordNewRouteImport } from './routes/_app.health-record.new'
import { Route as AppFarmsFarmIdRouteImport } from './routes/_app.farms.$farmId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVetRoute = AppVetRouteImport.update({
  id: '/vet',
  path: '/vet',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppIotRoute = AppIotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => AppRoute,
} as any)
const AppImageAnalysisRoute = AppImageAnalysisRouteImport.update({
  id: '/image-analysis',
  path: '/image-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmsRoute = AppFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoRoute = AppDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetRoute = AppDatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsIdRoute = AppPredictionsIdRouteImport.update({
  id: '/predictions/$id',
  path: '/predictions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRecordNewRoute = AppHealthRecordNewRouteImport.update({
  id: '/health-record/new',
  path: '/health-record/new',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmsFarmIdRoute = AppFarmsFarmIdRouteImport.update({
  id: '/$farmId',
  path: '/$farmId',
  getParentRoute: () => AppFarmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/alerts': typeof AppAlertsRoute
  '/assistant': typeof AppAssistantRoute
  '/dashboard': typeof AppDashboardRoute
  '/dataset': typeof AppDatasetRoute
  '/demo': typeof AppDemoRoute
  '/farms': typeof AppFarmsRouteWithChildren
  '/image-analysis': typeof AppImageAnalysisRoute
  '/iot': typeof AppIotRoute
  '/learn': typeof AppLearnRoute
  '/onboarding': typeof AppOnboardingRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/vet': typeof AppVetRoute
  '/farms/$farmId': typeof AppFarmsFarmIdRoute
  '/health-record/new': typeof AppHealthRecordNewRoute
  '/predictions/$id': typeof AppPredictionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/alerts': typeof AppAlertsRoute
  '/assistant': typeof AppAssistantRoute
  '/dashboard': typeof AppDashboardRoute
  '/dataset': typeof AppDatasetRoute
  '/demo': typeof AppDemoRoute
  '/farms': typeof AppFarmsRouteWithChildren
  '/image-analysis': typeof AppImageAnalysisRoute
  '/iot': typeof AppIotRoute
  '/learn': typeof AppLearnRoute
  '/onboarding': typeof AppOnboardingRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/vet': typeof AppVetRoute
  '/farms/$farmId': typeof AppFarmsFarmIdRoute
  '/health-record/new': typeof AppHealthRecordNewRoute
  '/predictions/$id': typeof AppPredictionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dataset': typeof AppDatasetRoute
  '/_app/demo': typeof AppDemoRoute
  '/_app/farms': typeof AppFarmsRouteWithChildren
  '/_app/image-analysis': typeof AppImageAnalysisRoute
  '/_app/iot': typeof AppIotRoute
  '/_app/learn': typeof AppLearnRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/vet': typeof AppVetRoute
  '/_app/farms/$farmId': typeof AppFarmsFarmIdRoute
  '/_app/health-record/new': typeof AppHealthRecordNewRoute
  '/_app/predictions/$id': typeof AppPredictionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/alerts'
    | '/assistant'
    | '/dashboard'
    | '/dataset'
    | '/demo'
    | '/farms'
    | '/image-analysis'
    | '/iot'
    | '/learn'
    | '/onboarding'
    | '/reports'
    | '/settings'
    | '/vet'
    | '/farms/$farmId'
    | '/health-record/new'
    | '/predictions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/alerts'
    | '/assistant'
    | '/dashboard'
    | '/dataset'
    | '/demo'
    | '/farms'
    | '/image-analysis'
    | '/iot'
    | '/learn'
    | '/onboarding'
    | '/reports'
    | '/settings'
    | '/vet'
    | '/farms/$farmId'
    | '/health-record/new'
    | '/predictions/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/alerts'
    | '/_app/assistant'
    | '/_app/dashboard'
    | '/_app/dataset'
    | '/_app/demo'
    | '/_app/farms'
    | '/_app/image-analysis'
    | '/_app/iot'
    | '/_app/learn'
    | '/_app/onboarding'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/vet'
    | '/_app/farms/$farmId'
    | '/_app/health-record/new'
    | '/_app/predictions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vet': {
      id: '/_app/vet'
      path: '/vet'
      fullPath: '/vet'
      preLoaderRoute: typeof AppVetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iot': {
      id: '/_app/iot'
      path: '/iot'
      fullPath: '/iot'
      preLoaderRoute: typeof AppIotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/image-analysis': {
      id: '/_app/image-analysis'
      path: '/image-analysis'
      fullPath: '/image-analysis'
      preLoaderRoute: typeof AppImageAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/farms': {
      id: '/_app/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof AppFarmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo': {
      id: '/_app/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AppDemoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dataset': {
      id: '/_app/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof AppDatasetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/predictions/$id': {
      id: '/_app/predictions/$id'
      path: '/predictions/$id'
      fullPath: '/predictions/$id'
      preLoaderRoute: typeof AppPredictionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health-record/new': {
      id: '/_app/health-record/new'
      path: '/health-record/new'
      fullPath: '/health-record/new'
      preLoaderRoute: typeof AppHealthRecordNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/farms/$farmId': {
      id: '/_app/farms/$farmId'
      path: '/$farmId'
      fullPath: '/farms/$farmId'
      preLoaderRoute: typeof AppFarmsFarmIdRouteImport
      parentRoute: typeof AppFarmsRoute
    }
  }
}

interface AppFarmsRouteChildren {
  AppFarmsFarmIdRoute: typeof AppFarmsFarmIdRoute
}

const AppFarmsRouteChildren: AppFarmsRouteChildren = {
  AppFarmsFarmIdRoute: AppFarmsFarmIdRoute,
}

const AppFarmsRouteWithChildren = AppFarmsRoute._addFileChildren(
  AppFarmsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatasetRoute: typeof AppDatasetRoute
  AppDemoRoute: typeof AppDemoRoute
  AppFarmsRoute: typeof AppFarmsRouteWithChildren
  AppImageAnalysisRoute: typeof AppImageAnalysisRoute
  AppIotRoute: typeof AppIotRoute
  AppLearnRoute: typeof AppLearnRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVetRoute: typeof AppVetRoute
  AppHealthRecordNewRoute: typeof AppHealthRecordNewRoute
  AppPredictionsIdRoute: typeof AppPredictionsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDatasetRoute: AppDatasetRoute,
  AppDemoRoute: AppDemoRoute,
  AppFarmsRoute: AppFarmsRouteWithChildren,
  AppImageAnalysisRoute: AppImageAnalysisRoute,
  AppIotRoute: AppIotRoute,
  AppLearnRoute: AppLearnRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVetRoute: AppVetRoute,
  AppHealthRecordNewRoute: AppHealthRecordNewRoute,
  AppPredictionsIdRoute: AppPredictionsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
